apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: fake-user:psp:restricted
    namespace: psp-example
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: psp:restricted
  subjects:
  - kind: ServiceAccount
    name: fake-user
    namespace: psp-example
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
